### ISSUE TITLE
REPLToggle produces NameError: name 'newcodes' is not defined on Ubuntu WSL only

### ISSUE THREAD

**Issue by shy00n** [sillybun/vim-repl#98]
**Describe the bug**
When I hit REPLToggole:
```
"ZYTREPL1 [running]" [Modified] --No lines in buffer--
Error detected while processing function repl#REPLToggle[42]..repl#ToREPLPythonCode:
line   23:
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/home/syoon/.vim/plugged/vim-repl/autoload/formatpythoncode.py", line 392, in format_to_repl
    pc.getcode(codes)
  File "/home/syoon/.vim/plugged/vim-repl/autoload/formatpythoncode.py", line 39, in getcode
    self.mergeunfinishline()
  File "/home/syoon/.vim/plugged/vim-repl/autoload/formatpythoncode.py", line 114, in mergeunfinishline
    tobeadded = self.rawcontents[j]
IndexError: list index out of range
line   24:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'newcodes' is not defined
E858: Eval did not return a valid python object
```

**Screenshots**

**Desktop (please complete the following information):**
~/.vim$ uname -a
Linux DESKTOP-3DKM78D 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/72399256/96190777-c2619300-0f10-11eb-8da5-e13a5444baa7.png)

 - result of `:REPLDebugInfo`
```
VIM-REPL, last update: 2019.8.23
Operation System: Linux
Support python3: 1
Support python: 0
has +terminal: 1
has +timers: 1
3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0]
REPL program:
{'vim': ['vim -e'], 'perl': ['/home/syoon/.vim/plugged/vim-repl/ftplugin/perl/psh'], 'lua': ['lua'], 'default': ['bash'], 'python':
['python']}
lua for lua is not executable.
REPL exit commands:
{'vim': 'q', 'zsh': 'exit', 'ptpython': 'quit()', 'lua': 'os.exit()', 'default': 'exit', 'bash': 'exit', 'R': 'q()', 'python': 'quit()', 'ipython': 'quit()'}
Current File Type: python
Current Type: python
Current Exit Commands: quit()
```
**Additional context**
This does NOT happen with Windows 10 but they both share .virmc or _vimrc files via symlink
```
 ln -fs /mnt/c/Users/alive/_vimrc .vimrc
```
Works well after the initial error msg. Would be happier without the error message:
Plug Installed
 91 call plug#begin('~/.vim/plugged')
 93 Plug 'sillybun/vim-repl'
 96 Plug 'vim-scripts/indentpython.vim'
 97 Plug 'ahw/vim-pbcopy'
 100 Plug 'vim-airline/vim-airline'
101 Plug 'vim-airline/vim-airline-themes'
102 Plug 'majutsushi/tagbar'
105 Plug 'nvie/vim-flake8'
108 Plug 'tmhedberg/SimpylFold'
109 Plug 'scrooloose/nerdtree'
110 Plug 'jistr/vim-nerdtree-tabs'
111 Plug 'jnurmine/Zenburn'
112 Plug 'altercation/vim-colors-solarized'
113 Plug 'dracula/vim'
114 " Git commands
115 Plug 'tpope/vim-fugitive'
116 call plug#end()

**Comment by shy00n** [comment]
Seem to be a problem only when virtual env is used in pyenv.
Not a show stopper but only a minor issue

**Comment by shy00n** [comment]
Went away with new ppa upgrade of vim to 8.2 & wipe of Plugs directory. So, no issues.
